### ISSUE TITLE
Feedback from Mike re: "Can we contact you for more feedback about this issue?" on survey

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#106]
"This shouldn't be a yes or no question. My first instinct was to write the word yes or no here instead of leaving contact information [or leaving it blank]"

**Comment by mathias-gibson** [comment]
Is he talking about the web or text survey? the text survey captures their number, so the yes in textitin drops it in a follow up "follow-up" group, while a no drops it in a "donotcontact" group. so it is a yes or no response for text.

**Comment by ErnieAtLYD** [comment]
@mathias-gibson, Mike was talking about the web survey.

It does bring up something different though: so if there's a yes/no for text and NOT a yes/no for web that can bring up an issue if we're building one interface to handle both issues. How can the interface be designed so a series of questions can be used on both interfaces?

**Comment by mathias-gibson** [comment]
true, this is another one of those concessions we make by having text and web synced, along with limiting the number of questions. I guess we can just ask the user to enter the number or email they'd like to be contacted by in both, skipping the efficiency provided by caller id in the name of synchronization

**Comment by mathias-gibson** [comment]
dont want to set expectation that every question will be followed up with, by asking for this question, going to add it it to the "any other comments" question
