### ISSUE TITLE
Users should be able to add, remove and choose the order of dashboard widgets.

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#111]
if this is the case, this probably means a lot more control will be moved from the python side to the javascript side. There may need to be a giant javascript object, and then in JS each of those widgets may have to be dynamically created for the dashboard to display.

See #87.

**Comment by phiden** [comment]
Blocked by #195

**Comment by mathias-gibson** [comment]
should they? now that we are simplifying the db to mostly feedback stuff and pulling in fewer datasets and have narrowed the use case, this seems less important

**Comment by phiden** [comment]
It might be. It's a conversation for our next planning meeting.
