### ISSUE TITLE
Take Socrata data > backend > push out to front end in JSON format

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#124]
- [ ] Bring in Neighborhood Compliance and Code violation data from https://opendata.miamidade.gov/311/RER-311-Cases/tzia-umkx
- [ ] Building permits data from https://opendata.miamidade.gov/dataset/Building-Permits-Issued-by-Miami-Dade-County-Jan-2/awsz-tanw?

(More to be added later)

**Comment by mathias-gibson** [comment]
https://opendata.miamidade.gov/311/RER-311-Cases/tzia-umkx

**Comment by ErnieAtLYD** [comment]
This is from an [LA dashboard](http://lamayor.org/dashboard) that uses a chart to bring in Socrata data:
- http://datala.github.io/bradley-tower/
- https://github.com/datala/bradley-tower/blob/master/_includes/viz/jobs.html

**Comment by ErnieAtLYD** [comment]
Ideally this should be done ASAP after we get the updated datasets from Socrata. The hope is that this can be knocked out by **8/11**, revisiting as needed.

**Comment by ErnieAtLYD** [comment]
Let's try a different strategy to this. Because the issue seems to be happening on a dashboard widget by widget basis let's open up tickets that reflect the status of each.
