### ISSUE TITLE
Get BSS Data into Socrata Dataset

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#125]
Mike has view only access, waiting for them to create Socrata job

**Comment by mathias-gibson** [comment]
in queue for Sayed at CIAO, but no eta yet

**Comment by mathias-gibson** [comment]
@sarasti, do we have an update on this guy? Not sure if you know how/where to find plans tracking data, I still havent tracked down the DB but have an open question to Donna

**Comment by ErnieAtLYD** [comment]
Moved to the tech/user google document, closing as an issue since county won't be using this repo directly.
