### ISSUE TITLE
Get 24hr ConPers IVR Phone Data into Socrata

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#126]
Mike has view only access, waiting for them to create Socrata job

**Comment by ErnieAtLYD** [comment]
Update from @mathias-gibson on a call he had with @sarasti: "their access to their own call center analytics is bonkers, and they don't track the data well, and their vendor doesn't allow programmatic access so we are left with hacking a solution, which might fall through. that is to say, i'm not holding my breath on phone data."

**Comment by phiden** [comment]
Moving this to maybe later, since @sarasti made it pretty clear that we're not going to get this before Summit.

**Comment by mathias-gibson** [comment]
sounds good, I closed the PIC call center one since that's been verified as
a dead end. this one is probably also a pipe dream, if they even tracked it
down​

**Comment by ErnieAtLYD** [comment]
Moved to the tech/user google document, closing as an issue since county won't be using this repo directly.
