### ISSUE TITLE
Get PIC Call Center Data in Socrata

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#127]

**Comment by sarasti** [comment]
Testing reply from Waffle

**Comment by mathias-gibson** [comment]
from mike "The reporting tool we have to generate this txt file does not seem to come with a scheduler. Someone would literally have to run it and upload it regularly.

Direct Access to the DB might be an option, but you’d still need someone who understands that data set to create this job. Truthfully – I think they only people that understand that DB are Avaya. It would be consulting project"

**Comment by phiden** [comment]
Assuming this is different from #126, moving into Maybe Later because of above blocker.

**Comment by mathias-gibson** [comment]
this is not gonna happen anytime soon, time to say our sweet goodbyes :(
