### ISSUE TITLE
Add Google Analytics to Apps

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#132]

**Comment by ErnieAtLYD** [comment]
@mathias-gibson: see if you can get tracking code HTMLs for the dashboard app (and the wizard too while you're in there) - and then send me the HTML so I can put it in the footer OR I'll teach you how to go in and edit the code yourself.

**Comment by phiden** [comment]
@mathias-gibson were you able to get this tracking code?

**Comment by mathias-gibson** [comment]
Havent looked into it, was planning on checking in on it tomorrow. Is this
blocking anything?
