### ISSUE TITLE
Make the UI look as close to final (Due 8/31)

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#133]
- [x] replace placeholders with actual data where possible (8/14)
- [x] create the charts for that data (8/14)
- [x] CSSing that needs to get done

**Comment by phiden** [comment]
Added blocked label -- I'm still playing with the CSS, but the pulling in and charting of data has gotten as far as I can get it. Which is to say, I've charted what data we have.

**Comment by ErnieAtLYD** [comment]
Also a reminder to help Ernie move some of the inline CSS he did for last minute dashboard changes into SASS and making things look generally less awful. (Sorry about that)
