### ISSUE TITLE
"View Details" page for Survey dashboard widgets

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#134]
- [ ] Sophia to wireframe / spec out / provide Ernie with what information is needed to build out content
- [ ] Ernie to provide Sophia with JSON objects or forms if needed

**Comment by phiden** [comment]
Is there a way to auto-generate a URL for these pages in Python/Jinja, that passes either the ID of the parent <div> or the URL for the data call?

**Comment by ErnieAtLYD** [comment]
@phiden: would we want to auto-generate though? I had imainged that each section would have really specific looks that may be unique. For example, I had initially envisioned all the user survey widgets would go to a combined user survey detail page. Permit metrics would have their own user detail pages, neighborhood compliance, etc. 

And because of that, they would kind of have their own unique looks. What do you think?

**Comment by phiden** [comment]
You're probably right -- what I'll do is develop some templates and establish a naming convention, so that if we want to put a UI over building those pages at some point we can.

**Comment by phiden** [comment]
Moving to 'maybe later' because we've actually removed the `view details` links from most charts.
