### ISSUE TITLE
Add labels to JSON survey pie chart object

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#135]
<img width="1161" alt="feedback" src="https://cloud.githubusercontent.com/assets/33945/9124401/69c46f30-3c4b-11e5-8024-04b9631d036b.png">

Sophia, let me know how you would need me to send you the data as well, and whether or not it should be in MVP versus MVP + 1.

**Comment by ErnieAtLYD** [comment]
Related to #133.

**Comment by phiden** [comment]
MVP, JSON in any structure.

**Comment by ErnieAtLYD** [comment]
@phiden, JSON will be in the form of the following:

```
<script type="application/json" id="jsondata">
{"series": [{"data": [2, 0, 0, 0, 0, 0, 0]}], "datetime": {"data": ["08-04", "08-05", "08-06", "08-07", "08-08", "08-09", "08-10"]}}
{"sms_en": 1, "web_en": 1, "sms_es": 0, "web_es": 0}
</script>
```

**Comment by ErnieAtLYD** [comment]
Syke, no it won't. It'll be in the form of this:

```
<script type="application/json" id="jsondata">
{"series": [{"data": [2, 0, 0, 0, 0, 0, 0]}], "datetime": {"data": ["08-04", "08-05", "08-06", "08-07", "08-08", "08-09", "08-10"]}}
</script>
<script type="application/json" id="jsondata">
{"sms_en": 1, "web_en": 1, "sms_es": 0, "web_es": 0}
</script>
```

**Comment by phiden** [comment]
Closed with last commit.

**Comment by ErnieAtLYD** [comment]
Ernie needs to add the labels into the JSON object he gives Sophia.

**Comment by ErnieAtLYD** [comment]
@phiden, I'm going to change the Javascript object to the following:

```
{
    "labels": {
        "sms_en": "SMS (EN)",
        "web_en": "Web (EN)",
        "sms_es": "SMS (ES)",
        "web_es": "Web (ES)"
    },
    "data": {
        "sms_en": 0,
        "web_en": 0,
        "sms_es": 0,
        "web_es": 0
    },
    "title": "Survey Type - Last 7 Days"
}
```

Is that okay? If so I will check in what I got through a second branch and pull request for you to work on.

**Comment by phiden** [comment]
Go ahead and I’ll fix it later.

**Comment by ErnieAtLYD** [comment]
Okay @phiden, head to the `135-piechart-labels` branch and continue the work from here - I'm going to reassign this to you now!
