### ISSUE TITLE
Add MDC Building web analytics as dashboard data

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#137]
wondering whether it might be useful to add web traffic to their website to provide more insight on user behavior

**Comment by ErnieAtLYD** [comment]
@mathias-gibson: how would this directly tie into the dashboard?

**Comment by ErnieAtLYD** [comment]
(Also related to #132)

**Comment by ErnieAtLYD** [comment]
If we are taking the stats of the building website and putting it on a dashboard, my gut says that would provide value more to internal employees to the public. It would also be a tricky thing to build due to needing to extract the value from the Analytics, not the website itself.

I'm also not sure if it'd be a must have feature. I'm open to this being an "In the future" task, however.

**Comment by mathias-gibson** [comment]
yeah, i added it to mvp+1, but this is analytics on their website, where as 132 is on analytics on our tool for our team metrics. you think this info would be more valuable to the public than gov staff? I think most of the dashboard content will be geared toward gov staff, they are the primary users in my opinion, the info that we're looking to make transparent with the public imo is feedback results, but whether we create separate internal/external versions is an mvp+1 isssue

**Comment by ErnieAtLYD** [comment]
I don't understand what you're trying to say. What you give specific
examples of metrics you would want to see on a dashboard from the building
department?

**Comment by mathias-gibson** [comment]
this would be traffic to certain parts of miamidade.gov/building to show
how traffic compares on certain apps or services on their website, to
correlate policy or service changes with online activity (just an idea,
need to validate usefulness during user testing, so feel free to ignore for
now if it seems like too big of a lift)

**Comment by phiden** [comment]
Do we have this data?

**Comment by mathias-gibson** [comment]
theoretically we have access to their google analytics, organizing and
making sense of them is the lift, might make sense to rebuild all the
filters and tracking, but I need to spend a good day studying up on the
stuff since it aint easy​

**Comment by ErnieAtLYD** [comment]
Moved to the tech/user google document, closing as an issue since county won't be using this repo directly.
