### ISSUE TITLE
public/staff versions of dashboard

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#138]

**Comment by ErnieAtLYD** [comment]
What do you mean by this? Is there an action item? Something to decide?

**Comment by mathias-gibson** [comment]
Of the dashboard, creating separate views for employees and the public

**Comment by ErnieAtLYD** [comment]
This is part of the admin functionality that we talked about earlier on
Monday and part of MVP + 1. Is there a particular piece of functionality
you are talking about?

**Comment by mathias-gibson** [comment]
Maybe not, feel free to close

**Comment by phiden** [comment]
- [ ] create a second dashboard display that shows instead of the primary IF the user is not logged in.
- [ ] secondary dashboard should display widgets as defined by Admin panel.

**Comment by phiden** [comment]
Blocked by #111 - widgets need to be define-able by the Admin panel.

**Comment by mathias-gibson** [comment]
what would be different about the two dashboards? possibly visibility of open ended feedback? Those would probably be linked to on a sub page anyway. we need to think about this one
