### ISSUE TITLE
Is there any way to take the Socrata branding out of the maps?

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#143]
LA seems to do this with their permit map. May be possible by reaching out to a Socrata contact:
https://performance.lacity.org/en/stat/goals/8ya7-fqzd/tpjh-8a6z/fsx8-eifx

Otherwise we may need to take the data out directly and feed it into leaflet.js.

**Comment by phiden** [comment]
@ErnieAtLYD let me know if you get a response on this; I'm happy to take data and incorporate to leaflet.

**Comment by phiden** [comment]
I think at MVP+1 or +2, we should scrap that Socrata map in favor of a leaflet one. It’s horrifying and has way too much functionality for what we need.
