### ISSUE TITLE
As a dashboard viewer, I want to know the average cost per each permit.

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#147]
To do this we try to get the average total fees charged for a permit in a 30 day period.
month/ avg total fees charged for a permit. **This would return a dollar amount.**

However, the [Building data set](https://opendata.miamidade.gov/dataset/Building-Permits-Issued-by-Miami-Dade-County-Jan-2/awsz-tanw?) does not have a cost associated with a permit so we are blocked on this until the V2 data sets come in.

**Comment by phiden** [comment]
@sarasti In this data set, there's a column listed as "estimated value." What does that represent?

**Comment by ErnieAtLYD** [comment]
From Sarasti: "On my phone but it's usually cost to do that actual work - it's an estimate of what you are paying the contractor to do the actual work."

**Comment by ErnieAtLYD** [comment]
After consultation with @mathias-gibson we're going to push this in the "not know maybe later" bucket. I'll do this by removing it from the milestone.

**Comment by ErnieAtLYD** [comment]
We actually did this now and it's implemented in the dashboards, yay!
