### ISSUE TITLE
Staging is ignoring a good chunk of CSS

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#155]

**Comment by phiden** [comment]
Suspect it's a CSS file not getting pulled in. I'm working in style.css -- maybe it's not getting compiled properly into common.css.

**Comment by ErnieAtLYD** [comment]
UGH. So after doing some digging we mention in our settings.py file this statement:

```
ASSETS_DEBUG = True  # Don't bundle/minify static assets
```

which sets it so that assets aren't bundled. Soooo we can mark this as closed.
