### ISSUE TITLE
As a dashboard user I would like to see number of neighborhood compliance violations over time.

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#156]
@mathias-gibson, in your metrics spreadsheet you have the x/y listed as over the course of a month, but in the time frame column you list wanting to chart it over the course of a year. Any preferences?

If it's violations by month for the past 12 months, this is the API URL and @phiden is good to start charting this out:
https://opendata.miamidade.gov/resource/tzia-umkx.json?$select=date_trunc_ym(ticket_created_date_time)%20AS%20month,%20count(*)%20AS%20total&$group=month&$order=month%20desc&$limit=12&$offset=1

But I want to verify it with you first.

**Comment by mathias-gibson** [comment]
yeah, code violations by month for the past year is what I was envisioning

**Comment by ErnieAtLYD** [comment]
Okay - @phiden, I'm re-assigning this to you but you to add into the dashboard, same thing as the similar data call.
