### ISSUE TITLE
As a dashboard viewer I would like the see all the different violation types in the past 30 days

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#157]
Note that the API of what I believe is the way to group types currently returns an error and is blocked by Socrata:

https://opendata.miamidade.gov/resource/tzia-umkx.json?$select=issue_type,%20count(*)%20AS%20total&$group=issue_type&$limit=5

**Comment by phiden** [comment]
Did the ETL, so this is working now. Might recommend that we don't show _all_ the different violation types as it clutters the chart, but take a look.
