### ISSUE TITLE
As Christa, I'd like to see the % of plans that had 2 or more reviews for the same trade so that we can investigate inefficiencies

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#158]
@mathias-gibson - if we were to go forward with this, 
- [ ] What dataset would we use? Plans review? Permits?
- [ ] What specifically would we need to check for to verify there are two or more reviews for the same trade?

If we don't have a clear way on how to solve this, this is something we must push back unfortunately.

**Comment by mathias-gibson** [comment]
id like to track this on the metrics dashboard doc, gonna talk to donna about this one on monday, but might not be something we can access
