### ISSUE TITLE
Limit violations data to 2015

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#173]
Given this:

https://opendata.miamidade.gov/resource/tzia-umkx.json

Limit the response to tickets opened in 2015.

**Comment by ErnieAtLYD** [comment]
Hey @phiden - so this is the query for those same tickets opened after 1/1/2015:

https://opendata.miamidade.gov/resource/tzia-umkx.json?$where=ticket_created_date_time%20%3E%20%272015-01-01%27

Is that what you're looking for?

**Comment by phiden** [comment]
I think so!

**Comment by ErnieAtLYD** [comment]
Awesome. Going to close this ticket then :)
