### ISSUE TITLE
Typo in English textitin survey

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#175]
`Whats your email?` should be `What's your e-mail?` or `What is your e-mail address?`
Also, it seems very randomly placed between "How could the County improve..." and "Text the number that corresponds to your role..."

Also, on the "Can we contact you..." there needs to be a `.` at the end of "Please provide your e-mail..."

**Comment by mathias-gibson** [comment]
Hm, "Whats your email?" isnt part of the flow. The flow goes: 

"Can we contact you for more feedback on this issue? Text yes or no. Please provide your email if that is how you would prefer to be contacted"

followed by:

"Thanks for your response. Your feedback will help inform the County on how to improve its processes and track its progress."

added a period to the can we contact you box
