### ISSUE TITLE
Typos in Spanish TextItIn survey

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#176]
In "Prefiere enviar su solicitud..." `"Texto" should be "Textea el numero '1' para 'en linea', o '2' para 'en persona.'"`

`Whats your email` displays again, untranslated and randomly between how to improve and what's your role. 

In "Podemos contactar con ud....", `texto` should be `textea`. Also, why are they responding 'y' or 'n' for yes and no instead of 's' or 'n'? On the english survey, it's a full "yes" or "no" -- suggest changing to 'sí' and 'no'.

**Comment by mathias-gibson** [comment]
thanks! changes made. also fixed bug behind "Whats your email" (it was triggering the test flow when you entered test as a response)
