### ISSUE TITLE
Data for # of surveys completed is incorrect

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#177]
The data that feeds the pie chart is showing 0 surveys completed for all surveys. Typeform, at least, has 11 completed surveys across both languages.

Related to #135

**Comment by ErnieAtLYD** [comment]
So we talked about this - we think this was an issue with caching on both our end and typeforms end. We also realized that although there are 11 completed surveys, only 2 were completed in the last 7 days. 

Closing as a non-issue.
