### ISSUE TITLE
Leaflet map doesn't work on https staging

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#182]
https://mdc-feedback-stage.herokuapp.com/

(Note the `https` versus `http`. I may have some ideas from the work we did here on amiinmiami. Giving a heads up to @phiden but I THINK I know what to do here unless you want to work on this.)

**Comment by phiden** [comment]
I'll leave this one to you, since you have a lead on it.

**Comment by ErnieAtLYD** [comment]
Leaflet does now work in staging, but I ended up using a different leaflet map. This may not be the one you like - it was an oversight when I replaced it. If that's the case, let's open up a new issue and we can talk it through oh how we can best tackle this. (It may just be a case where you use the old leaflet code you used, seeing if it works on staging again now that we've tweaked with the staging servers so much, and going from there.)
