### ISSUE TITLE
Create user management back-end

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#199]
- [x] create roles database table `superadmin` and `admin` access
- [x] Take Sophia's base UI and built it into the app as `/users/manage`
- [x] `superuser` has ability to add a new user (name, e-mail, ~~password,~~ permissions)
- [x] `superuser` has ability to delete a user wholesale
- [x] ~~all `user`s can change password through the same interface~~
- [x] all `user`s can see all other users' existence in user management interface
- [x] Ernie to combine "first name" + "last name" -> "full name"
- [x] ~~`system` sends e-mail to new user with login info~~
- [x] ~~`system` sends e-mail to existing user when info is changed.~~
- [x] UI for all of this -- see #198

**Comment by ErnieAtLYD** [comment]
Would edit "ability to add a new user" to "AS A SUPERUSER, I would like the ability to add a new user"

**Comment by ErnieAtLYD** [comment]
This will all be on the `user-roles` branch will I will be developing as i go along.

**Comment by ErnieAtLYD** [comment]
@phiden: how do you add the ability to edit someones profile, either your own or someone elses? Is that explicity allowed?

**Comment by phiden** [comment]
There's nothing to change expect password, which you can do from the UI I provided inline.

**Comment by ErnieAtLYD** [comment]
What it looks like if you do NOT have superadmin access and go to the `/user/manage` page:

<img width="1280" alt="feedback___user_user_manage" src="https://cloud.githubusercontent.com/assets/33945/9398981/dabe72ae-4762-11e5-90af-f426f362c912.png">
