### ISSUE TITLE
Take Mathias' textit and feed into datastore

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#20]
https://textit.in/api/v1

**Comment by mathias-gibson** [comment]
look at the API endpoint for flow runs https://textit.in/api/v1/runs. Eric Newcomer is the dude I fired questions at support@textit.in, but Jake/Dave might have advice as well

**Comment by ErnieAtLYD** [comment]
This is related to issue #30.
