### ISSUE TITLE
Decide on an inspector related analytic to include in the dashboard and implement it

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#219]
In lieu of #145 not being able to happen let's look through @mathias-gibson's analytics doc to see if there is a metric we can use that is inspector related that isn't total amount of inspections (which we can't measure due to the fields we have received.)

**Comment by mathias-gibson** [comment]
not a lot of data tracked on inspections, might be why Christa wanted us to
create some. I'll ping Donna to see if there is something that can be added
in v3.

in the mean time, two things we can add that will be interesting are time
eplapsed between application date and permit issues data, and time elapsed
permit issued date and co date. What makes this a bit messy is that the
dataset is all permits, regardless if they are subpermits, so we will need
to be able to suss out the main permits from subpermits that can be quickly
obtained online, and I don't think that's not as simple as grabbing those
with master permit numbers​.

**Comment by ErnieAtLYD** [comment]
- [ ] Time elapsed between `application_date` and `permit_issued_date`
- [ ] Time elapsed between `permit_issued_date` and `co_cc_date`

Question: For the second one - if there is no `co_cc_date` (the permit is open) do we calculate the time between the `permit_issued_date` and today's date? Or do we just skip over it?

> we will need to be able to suss out the main permits from subpermits that can be quickly
> obtained online, and I don't think that's not as simple as grabbing those
> with master permit numbers​.

So I've been treating main permits and subpermits as similar things - the biggest reason is because I don't know how to distinguish between the two (as you said)

**Comment by ErnieAtLYD** [comment]
Spinning off the metric that Mathias' brought up to #222, closing this issue.
