### ISSUE TITLE
Dashboard metrics: Time elapsed between application filings, permit issues and close dates

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#222]
- [x] Time elapsed between `application_date` and `permit_issued_date`
- [x] ~~Time elapsed between `permit_issued_date` and `co_cc_date`~~
- [x] Average lifespan of all open permits

Question: For the second one - if there is no `co_cc_date` (the permit is open) do we calculate the time between the `permit_issued_date` and today's date? Or do we just skip over it?

**Comment by ErnieAtLYD** [comment]
<img width="552" alt="feedback___dashboard_home" src="https://cloud.githubusercontent.com/assets/33945/9512635/c1988266-4c39-11e5-8eb5-f2e5a0a85c6f.png">

Added the application to permit issued date in weeks. I could do the time elapsed between permit issued date and closing date, but that is simply the total lifespan minus the application to permit issued date. @phiden, do you have any feelings about how this should look? If not I'm just going to check in the code and submit a pull request.

**Comment by phiden** [comment]
I would say if there's no `co_cc_date`, then instead of calculating the elapsed time between then and now, remove them from the data set and punt them over to a second listing: open permits, with an average lifespan.

**Comment by ErnieAtLYD** [comment]
There are over 60,000 open permits - I don't think I'm able to calculate the median age of all of them easily (Socrata limits me for querying a thousand at a time. I may just change the copy so that it says it's a "sample size" of 1,000.)

**Comment by phiden** [comment]
This is a good use case for details, maybe? is there any way to query the larger data set at all, or does Socrata just kill that?

**Comment by ErnieAtLYD** [comment]
@phiden: it doesn't, but there's a limit of 50,000 records. I could split it up into residential or commercial. BUT ALSO having the limit number super large does indeed slow down the site because I'm also going through every row, calculating the age, and applying the average to it.
