### ISSUE TITLE
allow time frames for metrics/viz to be adjust by user

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#229]
options of last 30 days, last 6 months, or last year? or for the graph that shows a calendar year, let them choose the year, or select a custom range?

**Comment by phiden** [comment]
Big lift. Moving to MVP+2.

**Comment by ErnieAtLYD** [comment]
So Sarasti argued for this as well separate from Mathias. Let's see what kind of additional opinions he has that wasn't picked up by Matty.

**Comment by sarasti** [comment]
So filters on the widgets would be amazingly useful. Since this is a Phase 2, Ernie - let's add it to things we'll be discussing with tech team here. I think it'll be essential to know how to do it in the future to keep the Dashboard fresh down the line.

**Comment by ErnieAtLYD** [comment]
We won't be able to get this in by time. Closing.
