### ISSUE TITLE
Make widget headlines clearer

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#230]
Kareem thinks "Average Commercial Permit Lifespan in the Last 30 Days" is a little unclear to folks who have no context of seeing this dashboard. How can we simplify this copy?

**Comment by phiden** [comment]
I don't know how much we can clear it up with headline language, but we could examine adding a "what's this?" to the widgets.

**Comment by ErnieAtLYD** [comment]
So talking with Donna, we learned that "Lifespan" isn't as important to folks as the time it takes from Permit Application to Permit Issuance. That's because once it's up to the owner, county cares less whether the owner/contractor takes 2 days or 2 years.

Because of that we may re-emphasize the lifespan widget. I'll close this BUT open up a slightly different ticket that clarifies that.
