### ISSUE TITLE
As a key stakeholder, I want to be able to receive periodical e-mails of user feedback so that I can complete the feedback loop and figure out who has been commenting what.

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#241]
- [ ] Break this up into smaller tasks

**Comment by ErnieAtLYD** [comment]
Heads up: This one will probably be a doozy and will consist of a bunch of smaller tasks which will need to be hammered out. We may need to push some of those tasks to a bunch of future sprints where necessary.

**Comment by mathias-gibson** [comment]
i was envisioning adding a question to the survey where the customer will select from the below sections and that feedback record would route to the emails associated (i have those, just not listing here):
Health
Fire
Contractor Licensing (Boards and Code)
Building
Electrical
Plumbing
Mechanical
Zoning
Neighborhood Compliance / Code Violations
Environmental Resources Management (DERM)
Cashier
Permit Application Intake and Information
Microfilm

**Comment by ErnieAtLYD** [comment]
Ernie to start break this up into smaller tasks

**Comment by phiden** [comment]
#298 is related.
