### ISSUE TITLE
Per Donna conversation, double check Top 20 violations list

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#243]
From Donna: "Huh. Why isn't JUNK AND TRASH / OVERGROWTH" on the Top 20 Violations by Type? I expected it to be number one on this list. COMMERCIAL VEHICLE / UNAUTHORIZED as well."

@phiden, do you want to double check that you have the Top 20 violations in the purple bar chart and not the Bottom 20 violations?

**Comment by phiden** [comment]
You can look at the details view for this, but I will confirm.
