### ISSUE TITLE
Histogram of new permits opened per month ends at 1/2015, not at current

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#254]
<img width="1271" alt="feedback___dashboard_home" src="https://cloud.githubusercontent.com/assets/33945/9700544/85c72d3a-53d4-11e5-98fc-fd2578972af0.png">

**Comment by phiden** [comment]
That's all that's in the dataset. This is the query: 
`https://opendata.miamidade.gov/resource/awsz-tanw.json?$select=date_trunc_ym(issuedate)%20AS%20month,%20count(*)%20AS%20total&$group=month&$order=month%20desc&$limit=12&$offset=2`

@ErnieAtLYD if you can give me a new query to get everything up to date, I can update the chart

**Comment by ErnieAtLYD** [comment]
Hey @phiden, here's your new API query to use:
`https://opendata.miamidade.gov/resource/kw55-e2dj.json?$select=date_trunc_ym(permit_issued_date)%20AS%20month,%20count(*)%20AS%20total&$group=month&$order=month%20desc&$limit=12&$where=master_permit_number=0&permit_type=%27BLDG%27`
