### ISSUE TITLE
As Rick & executives I would like to know the UMSA boundaries so that clustered map points do not confuse users

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#260]

**Comment by ErnieAtLYD** [comment]
Hey looking at this now and it looks like all the county is shaded although
there are boundaries. Can you take a look at this and ping me?

**Comment by phiden** [comment]
All the county is shaded. I have to figure out how to un-shade the municipalities — listed in a different issue.
