### ISSUE TITLE
As Rick I would like to add more context in regards to the code compliance points so that there's less confusion

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#261]
- [ ] Also consider showing a metric on which is open and closed or past due date? Open to interpretation here.

**Comment by phiden** [comment]
What did he mean by "more context" and/or "less confusion" -- what does he think is confusing, specifically?

**Comment by ErnieAtLYD** [comment]
I think it's back to the thought of the points on the map not having
context. There's a yellow dot - is it an open compliance case? Closed?
Overdue?

**Comment by phiden** [comment]
I see. For now, it’s just “all violations.” There is literally no context. I’m super happy that they’re asking for it, since the map was initially a “let’s just see what we can do” type thing.
