### ISSUE TITLE
Create json object of all surveys answers to feed into the app

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#262]
As Lourdes & Juliana I would like to see specific answers to feedback so that I can understand specific issues at the PIC in real time.

Do we show specific answers in a details page or on the dashboard main page? _BOTH_
- [x] create json object of all surveys answers to feed into the app
- [x] pull out a tag cloud or similar on main view (@phiden) 
- [x] create comments view on details page (@phiden)

**Comment by ErnieAtLYD** [comment]
@phiden, do you have specific thoughts about showing stats of particular answers? Should it be in the detail view? How about longer written answers? Would a table work? A word cloud? A combination of everything?

**Comment by ErnieAtLYD** [comment]
![asd-details](https://cloud.githubusercontent.com/assets/33945/9771277/0f87852a-5703-11e5-9791-836f84a45529.jpeg)

Back in 2007 they had data scientists that did reports and this was a format they used for Animal Services. Mike mentioned this was discontinued after budget cuts and he sees the benefit in the dashboard by basically being this - real time.

**Comment by phiden** [comment]
It’s not especially visual, but I think we can make it visual if we want to include that. On the dash, it could be a selected example, and the details view can have all the info.

**Comment by ErnieAtLYD** [comment]
:+1: Even for "making it visual"... what do you think about a table view? On a detail based page?

**Comment by phiden** [comment]
I dislike tables for the dashboard view. It defeats the "snapshot" purpose. But we can do tables on the detail page. A wordcloud might work for the dashboard view, especially if you could click in and get all the comments with that word.

**Comment by phiden** [comment]
but if the question is do I want to recreate that table in our dashboard, on the first view, then the answer is no, I don't. Too much text.

**Comment by phiden** [comment]
Maybe. Definitely not one that looks like that. I think it might be more functional, more scannable, if instead of a table it lays out like a comments view (since they _are_ comments) — Disqus-style or similar.

**Comment by ErnieAtLYD** [comment]
Sweet. BTW totally on board with you on not wanting to show walls of text on dashboard main. Let me aggregate all this into action items in a little bit
