### ISSUE TITLE
As Juliana I want to know % of successful inspections so that they're hovering at a standard rate of 20-25%

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#263]
- [ ] Add a dashboard metric which shows % of tickets w/ inspections that were successful (copy tweaking will be necessary)
- [ ] Discuss whether or not we want to split up inspections even more by district (this may be too large of a lift)

**Comment by mathias-gibson** [comment]
hm, i dont remember her asking for this to be on the db, we might want to confirm with her before adding (i remember her saying that it never changes so she doesnt need to check it). also unclear about the metric, what are "tickets" referring to ? this is just reporting how many insections passed/total, right? not a subset of inspections
