### ISSUE TITLE
Bar chart of Violations Detail Page should have largest violations at top, similar to main dashboard

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#264]
See https://mdc-feedback-stage.herokuapp.com/violations-detail/ - where the longest bars are at the bottom - versus https://mdc-feedback-stage.herokuapp.com where they are at the top.

**Comment by phiden** [comment]
Why reopen? The change just needs to push to staging.

**Comment by mathias-gibson** [comment]
I just edited the typo in the title, it was in the backlog column so I
didn't realize it was closed (maybe my waffle was lagging?)​
