### ISSUE TITLE
MOVE TO DETAILS VIEW: As Christa, I would like to hide the permit costs because they serve no purpose / contain inaccurate information

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#265]
Some thoughts:
- [x] ~~If the permit costs for permits is inaccurate, we should understand why. We should send an e-mail out to Donna inquiring for more information. Maybe it's a misplaced decimal? There are an awful lot of 00s in there. cc Christa and Mike on that one.~~ **Spun off as #266** 
- [ ] If the permit costs widget serve no purpose for executives, maybe we should just move it to a permit detail view anyway, especially if we give the public an opportunity to look at this.

**Comment by phiden** [comment]
Taking this one over, so I know which details views to build.
