### ISSUE TITLE
Consider adding twitter feed(s) to dashboard

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#267]
Christa noted that if this dashboard is for Executives, they want a reason to come back. If all the content gives the impression that it's static, that could prevent shareholders from coming back.

In particular she thought up the idea of a Twitter module. If we go with this solution we can use a widget search of "dade county building permits?" or tweets and responses from @MiamiDadeRER.

Thoughts, @phiden, @mathias-gibson?

**Comment by mathias-gibson** [comment]
hm, I don't remember her mentioning twitter, but I did bring this up as a
potential module a bit ago (though unsure of its value), with a hashtag or
twitter account for building. Presently this is a db for the building
process, not all of rer, so we'd probably want to narrow to it to building,
but wouldn't that require a certain amount of education about the hashtag
to use? not sure how  much people already use twitter to ​address the
building dept, but we could add info to the website and our posters that
mention to tweet @MiamiDadeRER with #building

**Comment by phiden** [comment]
It'd have to be something more unique than #building. That'd get hijacked real quick, and not even on purpose!

I'm kind of meh on the whole Twitter idea. I don't think tickers with public-generated content work especially well, and they usually need to be moderated. Putting a module that contains the county's accounts is more useful, IMO, but only for the public-facing dash.

**Comment by mathias-gibson** [comment]
yeah, its a matter of where we want to channel people, and I think Sophia's
right that if we open up twitter as a channel and encourage people to use
it, its gonna make addressing their feedback harder, whereas having them
coded through the survey (through department selection) allows them to be
routed to the right person. also, we get no contextual info about the
person through twitter.

**Comment by ErnieAtLYD** [comment]
Okay, let's push this to a maybe later sprint. I'm going to remove the MVP+1 Milestone.
