### ISSUE TITLE
As Christa, I want metrics that specific reveal "Who am I?" so that we understand surveys and permits at a granular level

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#268]
I think this applies to both user surveys as well as for dashboard metrics.
- [ ] Dashboard widget of what kind of user type is sending feedback (User details page?)
- [ ] We can also dig down permits by specific types: `permit_type`, `application_type`, `description`, `category_description1` and `category_description2` if applicable.
- [ ] #271 
- [ ] #273

**Comment by mathias-gibson** [comment]
not sure what task this issue is pointing to.  close it?

**Comment by ErnieAtLYD** [comment]
This was before the emphasis on exposing qualitative data and inspections.

Any way we can move this to the "someday" milestone instead?
