### ISSUE TITLE
build landing page to route users between eng and span surveys

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#272]

**Comment by phiden** [comment]
On which service? How do users get to the landing page? @mathias-gibson

**Comment by mathias-gibson** [comment]
this is for the web surveys, currently we're using cfa's paid version of
typeform that allows us to put logic into the survey and route the user to
english or spanish, but the free version doesn't have logic, an intro page,
or allow you to send users somewhere (the dashboard) once the survey has
been submitted.

so for the county to use the free version, we need to create an english
survey and a spanish survey, and have each linked to a button on this page,
who's url will be c4a.me/picsurvey​

**Comment by phiden** [comment]
Ok. Makes sense. However, I’m pushing it to the next sprint — this is way in the future still.

**Comment by mathias-gibson** [comment]
v3 draft in spanish - https://miamidadecounty.typeform.com/to/eEHiJU
v3 draft in english - https://miamidadecounty.typeform.com/to/F7hSOx

**Comment by mathias-gibson** [comment]
it would also be nice to have a finishing page if the county isnt aren't paying for typeform, bc currently hitting submit sends them to the below. That seems much harder, if possible. @ErnieAtLYD have you heard anything from Mike on that?

![screenshot 2015-09-15 14 16 09](https://cloud.githubusercontent.com/assets/8147336/9890371/68917df0-5bb4-11e5-8ac5-1f8d8b022622.png)

**Comment by phiden** [comment]
http://127.0.0.1:9000/choose-survey/
