### ISSUE TITLE
add surveys by purpose of visit histo

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#273]

**Comment by ErnieAtLYD** [comment]
Note to self: In the web version you can choose multiple versions AND choose an "option" option in the form of an array. In the text you can just get an integer.

So in the web version I'll have to aggregate all the arrays into its own thing and then add additional fields for each "other" option that has been chosen.

**Comment by ErnieAtLYD** [comment]
PR submitted, re-assigning to Sophia to make pretty
