### ISSUE TITLE
add survey complete tasks pie chart

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#274]

**Comment by ErnieAtLYD** [comment]
@mathias-gibson, can you give me more context?

**Comment by mathias-gibson** [comment]
theres a yes/no question in the survey that asks "did you get your stuff done"

**Comment by ErnieAtLYD** [comment]
@mathias-gibson: Did you imagine over 7 days or longer like 30?

**Comment by ErnieAtLYD** [comment]
Let's do 7 right now, just to get the point across. If we need to do 30 we'll add another task to myself. Results for the "Get Done" are either "Yes" or "1", depending on the API returned.

**Comment by ErnieAtLYD** [comment]
Re-assigning to @phiden to make into a chart.
