### ISSUE TITLE
add satisfaction rating by role and purpose and language

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#275]
- [x] add satisfaction rating by role
- [x] add satisfaction rating by purpose
- [x] add satisfaction rating by language

**Comment by ErnieAtLYD** [comment]
> "add satisfaction rating by role and purpose and language"

@mathias-gibson, can you explain this for more context?

**Comment by mathias-gibson** [comment]
we currently just have overall satisfaction rating. this is breaking it down by role (contractor, permit consultant, homeowner etc), purpose of visit (apply for a permit, deal with a violation) and language so that it is more detailed and has more meaning

**Comment by ErnieAtLYD** [comment]
This is blocked by #262.

**Comment by ErnieAtLYD** [comment]
PR submitted, re-assigning to Sophia to make pretty
