### ISSUE TITLE
Add a "what is this" to all metrics boxes

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#281]
For added context to each metric, add a tooltip "what is this" with further plain-English explanation of each measure. Related to #258

**Comment by phiden** [comment]
- [x] add ? to UI
- [x] on hovering ?, show tooltip (see Tipsy)
- [x] v1, we use google docs as the interface and database for entering that information, and pull it into our app via the API

**Comment by phiden** [comment]
https://docs.google.com/spreadsheets/d/170neJyhcBkg3sgABsqKk1B6WJa51r6oo6PEMAlwOBB8/edit#gid=0

**Comment by ErnieAtLYD** [comment]
Cool. Don't forget to link the google docs and the instructions to `README.md`.

**Comment by phiden** [comment]
thanks for that reminder :)
