### ISSUE TITLE
There is a question asking if the user wants follow-up on the SMS but not the web form

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#293]
Mathias, there's is a question asking if a user wants to be followed up on the SMS form in the form of a yes no answer, but not the web form.

Should we add a follow-up question to the web form, or drop the question on the SMS form? Let me know so I can standardize the answers - this blocks #262.

**Comment by mathias-gibson** [comment]
so this is something that might not be able to sync between the two. the way the question is asked in sms  is trying to make it easier on the user by using textitin's built in ability to capture the phone number and store it in a contact group without the user having to type out their number. In the web survey, we ask the question as part of the open-ended prompt. 

That said we could ask the user to just enter their phone number or email in sms surveys and bypass the convenience for the user in the name of syncing if its important, and have a dedicated open ended box for web and text asking for contact info.

If its a lot easier for data gathering to do it that way we can do it in a manual fashion
