### ISSUE TITLE
edit ending message to encourage user

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#295]
current - "Thanks for your response. Your feedback will help inform the County on how to improve its processes and track its progress.”

alternative
- Thank for taking the time to reach out to us. Your feedback will be shared with [mayor, commissioners and Department Director]. If you shared an issue that requires action, your response will be sent to the appropriate division director.

**Comment by ErnieAtLYD** [comment]
Something to the effect of "if you also provided any contact information someone may contact you if additional information is needed"? (Wording to be worked on)
