### ISSUE TITLE
draft inspection survey and provide web and text links to donna for letter

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#296]
- role
- exp start to finish
- have na option
- were you at the inspection (if not who was)
- did you have any concerns or recommendations
- add your permit number if you like

**Comment by ErnieAtLYD** [comment]
I can't help but think that this survey may be taken a LOT. Like for a big
nightmarish inspection, 2-3 times per inspection and then all the other
inspections for trade subpermits. That's a LOT of possible surveys and the
more questions there are the more questions someone would fill out.

That said, most of these questions do look pretty important. What's "have
na option?"

**Comment by mathias-gibson** [comment]
not all bullets listed were questions, some were just notes (have na option
was for the role I believe)

this survey will be <= 5 questions​

**Comment by ErnieAtLYD** [comment]
For reference where's the URL to that survey?

**Comment by mathias-gibson** [comment]
the shortlink i created is c4a.me/inspectionsurvey, but the change hasnt been
merged yet. the text inspector survey, which dont exist yet (waiting to hear
back from Christa), are planned to use codes 003 for english and 004 for spanish

On Thu, Sep 17, 2015 at 2:00 PM, Ernie Hsiung < notifications@github.com > wrote:
For reference where's the URL to that survey?
