### ISSUE TITLE
Pull in previously created Typeform & Textits to a dashboard

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#30]
GIVEN an existing typeform AND textit, be able to pull in results to the dashboard page. Waiting for @phiden to send me some workflows on how to do this.
- [x] Pull in the Typeform form ID and integrate results into the dashboard
- [ ] Pull in the TextIT ID and integrate results into the dashboard

**Comment by ErnieAtLYD** [comment]
Assigning this to @phiden as I'm waiting for her workflows. Sophia, if this is not the right thing to do let me know, thanks!

**Comment by phiden** [comment]
copy that, I’ll take a look!

**Comment by phiden** [comment]
@ernieatlyd are these results already available in your build, to display on a dashboard? If not, go ahead and take this task back and let me know when it's ready to go, so I can UI around it. Does that flow make sense?
