### ISSUE TITLE
Integrate mdc-feedback-frontend into surveys

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#31]
@phiden made https://github.com/codeforamerica/mdc-feedback-frontend. Integrate the page into the flow when a user chooses a survey.
- [x] Link trigger page to list of surveys
- [ ] Incorporate `layout.html` to all other pages
- [x] Move from bootstrap to skeleton

**Comment by phiden** [comment]
I believe this is done -- there's nothing left in the original repo to integrate. Closing the issue.
