### ISSUE TITLE
create signs to display by PIC computers

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#313]
![2015-09-01 10 29 28](https://cloud.githubusercontent.com/assets/8147336/9921345/792a3002-5c91-11e5-91e0-883d2595be73.jpg)
signs can go on desk in front of keyboard, or wall behind. could display both web and text survey, but stick to web if its too busy

**Comment by phiden** [comment]
@mathias-gibson do we have any formatting or sizing guidelines for this?

**Comment by mathias-gibson** [comment]
nope, i imagine an 8 1/2 x 11 on the glass backing or half sheet in front of the keyboard would do

**Comment by phiden** [comment]
Can you reach back out please and ask if they have any guidelines for that? Because if they don’t, they can just stick a PIC flyer there and save us and them the print process work.

**Comment by mathias-gibson** [comment]
hm, yes that's a good point, that reminds me that I wanted a specific
poster to point them to a desktop shortcut to the survey on the desktop of
the computer​ since I don't think they can surf the web on it. I'll get
back to you, can throw this under blocked for now.

​
