### ISSUE TITLE
Optimize Socrata (SODA) API usage

### ISSUE THREAD

**Issue by marks** [codeforamerica/mdc-feedback#319]
Hi there - I stumbled upon your usage of Miami Dade's Socrata portal and think this project looks great. I did notice that your API calls aren't using the newer, higher performance versions of the APIs.

For example,  `https://opendata.miamidade.gov/resource/kw55-e2dj.json` can be changed to `https://opendata.miamidade.gov/resource/vvjq-pfmc.json`. In addition to being faster overall, these new API endpoints include new features like more feature parity for SoQL with SQL such as LIKE and IN queries and much more.

You can learn more about the new features and how to find the new API endpoints at http://dev.socrata.com/changelog/2015/04/27/new-higher-performance-apis.html

Hope this helps!

**Comment by chrismetcalf** [comment]
:+1: 

Let me know if there's anything I can do to help!

**Comment by ErnieAtLYD** [comment]
@marks, had no idea. We'll put this in on our next push. Thanks for the heads up!

**Comment by marks** [comment]
@ErnieAtLYD sweet! You guys rock.
