### ISSUE TITLE
Give ability to add comma separated e-mail addresses to database table

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#360]
Full survey response, human-readable (no numbers), with contact information from database, to Christa please!

**Comment by ErnieAtLYD** [comment]
Hey Sophia, in what format would she like this in? Is this part of the whole monthly executive stuff? Or is she looking for something different, like a mass export through a CSV or something?

**Comment by phiden** [comment]
I think she wants a more daily report in order to support a quick response time — I’ll ask when we talk today, but I think a CSV export or similiar of _only_ the surveys that ask for follow-up would do the trick.

**Comment by phiden** [comment]
Per today's phone call, the following are our specs:
- Plain text/HTML e-mail of only the surveys that requested follow-up
- Once daily, if not twice daily, to the relevant party
