### ISSUE TITLE
Create monthly reporting mechanism for survey results

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#361]
- [ ] sanitized, human-readable, digestible monthly report from the surveys for the last month.
- [ ] all data, broken down by percentages with responses in that month. 
- [ ] specifically be able to show things like "other" -- what was the response there?

Effectively, a proper data report as opposed to a snapshot.

Deliverable should be formatted as: 
_\- a plain text e-mail with a PDF attachment that contains the report_
_Do we have a view in Typeform that has all this data, raw?_

**Comment by phiden** [comment]
@mathias-gibson working on drawing up the priorities -- once this wireframe/draft/etc is complete, reassign to @ErnieAtLYD

**Comment by ErnieAtLYD** [comment]
This has been done and live for a while.
