### ISSUE TITLE
Verify that the charts are showing all available data

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#368]
From Christa: "the dashboard shows 15 survey responses. Everything is broken down by groups of 15, except the purpose, which only shows 12 responses:"

**Comment by phiden** [comment]
Ok. The charts are _receiving_ all data, but they're not _showing_ all of it. The catch is that sometimes users are entering an open-ended text for "purpose" which doesn't match up with the purposes we're giving them (obtain a CU, meet with a reviewer, apply for a permit, meet with an inspector, find out about a violation/lien).

On the Javascript end, the code's looking for an integer between 1 and 5 to correspond to the stated purposes. When it doesn't get that, it ignores the data. 

See below for the console's logs of what's actually getting passed into our dashboard. The loop is the piece of data being passed in -- one for each survey response of a given type -- and the count is the number of times a given response has been entered in. IE, loop 0 is case "1", corresponding to "apply for a permit", and 5 survey respondents have said that was their purpose in going to the PIC.

```
loop 0, case: 1, count: 5
loop 1, case: 2, count: 5
loop 2, case: 4, count:  2
loop 3, case: 3, count: 1
loop 4, case: 6, count: 1
loop 5, case: beach club este en peligro y el condado sigue con su burocratismo,los vecinos nos estamos reuniendo y vamos a llamar ala television  para que se haga publico la falta de respeto del condado, count: 1
loop 6, case: 6 this is a text, count: 1
```

**Comment by phiden** [comment]
Blocked by decision as to how to modify either the survey question or the chart.

**Comment by ErnieAtLYD** [comment]
My suggestion: having an "other/write-in" option. In the above case, it would say there's 2 write-in answers.  And that would be pretty straightforward to do on the JS tip.

**Comment by phiden** [comment]
Say there's 2? What do you mean?

**Comment by ErnieAtLYD** [comment]
```
Option #1: *****
Option #2: ****************
Option #3: ***********
Option #4: *****
Option #5: ****************************
    Other: ****** 
```

Does that make a little more sense?

**Comment by phiden** [comment]
Yup, got it now. My fault -- mobile screwed up the formatting and cut off everything after "it would say there's 2" so it made zero sense! I said as much in Slack, but we can do that -- we just need to also pass in links and survey IDs for these responses so that there's a way to expose them in a details view while including context.
