### ISSUE TITLE
"Permits & sub-permits issued by type, Last 30 Days" should have a legend

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#389]
Sophia, can you work on this? Feel free to toss back if necessary. (What does MECH stand for? LPGX, etc). -E

**Comment by phiden** [comment]
Removing 'CCUT' per Donna: "A ccut is a Cookie Cutter not for permit.  This is not a real permit it is a shell permit that we use to create building permits for model developments.  I would eliminate this from the Dash board along with MMFP"
