### ISSUE TITLE
Remove municipal permits from the data set "Permits & sub-permits issued by type, Last 30 Days"

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#408]
- anything that starts with 'm'
- add copy to the ? text that indicates this filter

**Comment by ErnieAtLYD** [comment]
- Remove the Municipal Building, Municipal Plumbing, Municipal Electrical,  Municipal mechanical  
- Remove  Zoning improvement permits and Fire
- Separate from building the following categories and provide the appropriate label
- Roofing  Permit type Bldg categories 0092, 0095,  0096, 0107, 0106
- Windows  permit Bldg categories 82, 83, 84
- Storm Shutters and Awnings permit type bldg. categories 29, 0101
- Include both c numbers, N numbers and W, numbers in all counts
