### ISSUE TITLE
In SMS Spanish survey, intro copy should SMS before the first question

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#44]
![img_0190](https://cloud.githubusercontent.com/assets/33945/8735603/071c3adc-2bc7-11e5-863f-295cae93e468.PNG)

**Comment by mathias-gibson** [comment]
hmm, that's how its currently set up and how it displays on my phone. we
could try to squish into one message to ensure that doesn't happen, but
only have 27 characters...

**Comment by mathias-gibson** [comment]
ie, couldnt replicate, maybe an iOS issue. @phiden can you give the spanish text survey a try on your phone to see how the first texts order?

**Comment by phiden** [comment]
I can't replicate on iOS either. Closing this unfixed.
