### ISSUE TITLE
When not logged in, system throws attribute error

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#454]
When you visit a protected page while logged out, the system throws `AttributeError: 'AnonymousUserMixin' object has no attribute 'role'` instead of giving a login prompt.

**Comment by ErnieAtLYD** [comment]
@phiden I can't reproduce. Can you verify this is happening on both staging and localhost?

**Comment by phiden** [comment]
http://mdc-feedback-stage.herokuapp.com/users/manage, gone to directly without being logged in

gives "internal server error" on staging. Localhost is a whole other can of worms.
