### ISSUE TITLE
Spanish SMS options do not match with Spanish web options

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#46]
In the Spanish SMS version they are:  Contratista, arquitecto/a, consultor/a de permisos, desarrollador/a de bienes raíces, dueño/a de domicilio, dueño/a de negocio.

In the web version they are: contratista, arquitecto, consultor de permiso, dueño/a de casa, revelador, dueño/a de negocio.

The fourth and fifth options are different. Which one do we to use?

**Comment by mathias-gibson** [comment]
fixed - removed developer/revelador/desarrollador/a de bienes raíces from
all surveys
