### ISSUE TITLE
Not clear whether to texting "no" or "N" for questions

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#47]
See image. Basically, we ask the user that if they do not have a comment that they text "no," but when I text in the phrase "No" there's an additional message telling me I have to text "Y" or "N". This is confusing.

![img_0192](https://cloud.githubusercontent.com/assets/33945/8736043/3f73fde0-2bca-11e5-9e20-215813fe5b07.PNG)

**Comment by mathias-gibson** [comment]
how so? suggestions?

currently says "Can we contact you for more feedback about this issue? Text
"Y" for yes or "N" for no. Please provide your email if that is how you
would prefer to be contacted"

**Comment by ErnieAtLYD** [comment]
@mathias-gibson Look at the screenshot. If says "... if not, text 'no'." I text no and then it says "Please enter 'Y' or 'N'."

**Comment by mathias-gibson** [comment]
ah, you're talking spanish (sorry, was responding from email and didnt see the screenshot). i fixed that, we're all good
