### ISSUE TITLE
Will all charts and graphs be purple forever?

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#487]
If not, this is the official issue. If so, this is the official issue and you may mark it as closed. :)

**Comment by phiden** [comment]
So here's a thought. I asked Shelly for feedback on the app generally, and she suggested making everything a single color (and values thereof) instead of differentiating further, on the grounds that it's already clear which chart is which type. Thoughts? Obvs doesn't have to be purple.

**Comment by ErnieAtLYD** [comment]
I'm okay with that.
