### ISSUE TITLE
Give a heads-up e-mail to all the section leaders to tell them they will start getting follow-up e-mails so they are not surprised

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#490]
Hey @mathias-gibson can you handle this? I think sending them an e-mail letting them know will be a good heads up so they don't see a foreign e-mail and then just get sent to spam.

**Comment by mathias-gibson** [comment]
Happy to, though you'll be going to the pic in person to tell them about it
this week, right? I'll email Donna and ask her how she wants to notify the
section leaders, what's the email address and subject line for the email
they'll be receiving?

**Comment by ErnieAtLYD** [comment]
So in THEORY I am going to PIC. I haven't heard anything from Donna yet. I'm heads down writing a doc for Camilo so we can pair program together tomorrow. We can customize the subject line for the e-mail to whatever.

**Comment by mathias-gibson** [comment]
but will the emails continue to come from mdcfeedbackdev@gmail.com, or is
that going to change? I will email Donna and get that conversation rolling.
when is email routing  expected to go live?

**Comment by ErnieAtLYD** [comment]
> Will the emails continue to come from mdcfeedbackdev@gmail.com, or is that going to change?

That's a question we need to have; I know Pittsburgh has had difficulties getting it working. We should start it up with Donna on what her preferences are if we can do it easily.

> When is email routing  expected to go live?

E-mail routing can go live literally now if we wanted to, but it depends on if we want to give a heads up to staff or not. It's as simple as going to http://mdc-feedback-stage.herokuapp.com/users/manage (after logging in) and plugging the e-mails in.

**Comment by ErnieAtLYD** [comment]
Well, I was there in person to tell them how the section leaders would get e-mail follow-ups. It's safe to say they won't be surprised, I suppose.
