### ISSUE TITLE
Move certain variables from settings.py to configuration variable

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#515]
- The Gmail development e-mail address and passwords should be moved from settings.py to a configuration variable.
- The API keys (Typeform) should be moved from a settings.py file to a configuration variable as well.

**Comment by ErnieAtLYD** [comment]
@phiden and @mathias, note that once I produce a fix for this bug you will have to add two environmental variables, `MAIL_USERNAME` and `MAIL_PASSWORD`. Ask Ernie for the values. Sophia, you will need to add this to `$VIRTUAL_ENV/bin/postactivate` file.

**Comment by phiden** [comment]
Ok, please advise it’s fixed

**Comment by mathias** [comment]
I think you meant @mathias-gibson so sending him a notification ;)

**Comment by phiden** [comment]
No, I meant you, @ernieatlyd — please advise when fixed so I can add the vars to the $VIRTUAL_ENV.:)

**Comment by ErnieAtLYD** [comment]
(But I meant @mathias-gibson, yeah. Apologies! Stupid auto-complete.)

**Comment by phiden** [comment]
ohhh. What I get for not looking at the sender of the original message ;)
