### ISSUE TITLE
correction re: section email list in alphabetical order

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#529]
small issue: under "Set who receives e-mail" flip mechanical and microfilm to set alphabetical order

**Comment by phiden** [comment]
The order for these is getting set in the Python; reassigned to Ernie.

**Comment by ErnieAtLYD** [comment]
Believe it or not this is super difficult to do because they've already been set as constants. We'll have to close this as a wontfix.
