### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by phiden** [codeforamerica/mdc-feedback#535]
Given new formatting, saving a new user in the field wipes out everything that already existed. 

```
<form id="stakeholderForm" class="form form-stakeholders" method="POST" action="{{ url_for('user.user_manage') }}" role="form">
        <ul>
          {% for n in range(1,15) %}
          <li>

            {{ routes[n] }}: <input name="field-route-{{n}}" type="text" value="">

            <ul class='user-list'>

              {% if stakeholders[n-1] is defined %}
              <li>{{ stakeholders[n-1].email_list }}</li>
              {% endif %}

            </ul>

          </li>

          {% endfor %}
        </ul>

        <input type="submit" value="save changes">
      </form>
```

**Comment by phiden** [comment]
That is, if three users already exist in the DB, and I enter a new one, it wipes out the existing three.

**Comment by phiden** [comment]
related, if multiple users exist, it gets output as a comma-delimited list. Is there a way to spit them out as separate users, or should I JS this thing? 

![screen shot 2015-11-17 at 9 32 44 am](https://cloud.githubusercontent.com/assets/4895604/11219241/4040c636-8d0e-11e5-8ada-5d0088eb222e.png)

**Comment by ErnieAtLYD** [comment]
Long story short, we don't have enough time to completely change the format of the database since this is the last day. We'll just have to do this as is.
