### ISSUE TITLE
PIC Mainframe Dataset Update in Socrata

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#69]
Right now the following permit-related dashboard widgets need to be fed information:
- Permit Lifespan (Last 30 days)
- Average # of inspections per permit
- % of Permits completed within 15 days
- Cost per permit / average.

What is the strategy of getting this information long term? Where is the status of this now? In lieu of waiting for this information, is there any "hack" or stop-gap solution a developer can use to get this data? Can we use information that currently exists on the existing Open Data portal and if so, does it completely fit our needs?

**Comment by mathias-gibson** [comment]
we're waiting for  donna to give the thumbs up new columns for the mainframe data and also provide access to plans tracking data. we could fake it if we wanted or look for other open data portals that ould serve as a proxy. 

does lifespan = time to close? also where did % of Permits completed within 15 days come from?

**Comment by ErnieAtLYD** [comment]
Lifespan is equivalent to time to close.
% of permits completed with 15 days came from a similar dashboard from LA county. The said, they both use the same piece of information we don't have, a close date. Let me know if I'm mistaken on this.

So it looks like the following issues are open:
- [ ] wait for county to give the thumbs up new columns for the mainframe data 
- [ ] wait for county also provide access to plans tracking data

Is that correct?

**Comment by mathias-gibson** [comment]
Yeah, except Mike should be able to help us with updates to mainframe data,
we still need Donna to point toward the source of plans tracking data, I
sent her an email yesterday

**Comment by mathias-gibson** [comment]
CIAO has new dataset, just waiting for changes to be made to Socrata Dataset

**Comment by mathias-gibson** [comment]
update coming wednesday

**Comment by mathias-gibson** [comment]
Syed committed to updating on Friday

**Comment by ErnieAtLYD** [comment]
Got a text from Mike. Looks like there's an issue on the socrata side this time where the information that was given by MDC is not being parsed directly. I can still use the older dataset in the meantime but it looks like another follow-up will be needed for an update.

**Comment by sarasti** [comment]
As mentioned elsewhere - issues with Socrata. RER has done their part...We've set up the ETL job, but Datasync is failing for some reason. Working with Socrata all morning... They've asked us to work directly with "support". (I think they were implying don't hit up individuals like "Cam" on the side... but I think the end result was helpful. It seems they're a little more mobilized on solving this.)

**Comment by mathias-gibson** [comment]
just going to post the rough layout of columns Syed provided here:
PERMIT-ISSUED-DATE          
APPLICATION-DATE            
PERMIT-NUMBER               
PROCESS-NUMBER              
MASTER-PERMIT-NUMBER        
PERMIT-TYPE                 
RESIDENTIAL-COMMERCIAL      
ESTIMATED-VALUE             
APPLICATION-TYPE-CODE       
APPLICATION-TYPE-DESCRIPTION
PROPOSED-USE-CODE           
PROPOSED-USE-DESCRIPTION    
DETAIL-DESCRIPTION-COMMENTS 
FOLIO-NUMBER                
OWNER-NAME                  
LEGAL-DESCRIPTION-1         
LEGAL-DESCRIPTION-2         
PROPERTY-ADDRESS            
ARCHITECT-NAME              
CONTRACTOR-NUMBER           
CONTRACTOR-NAME             
CONTRACTOR-ADDRESS          
CONTRACTOR-CITY             
CONTRACTOR-STATE            
CONTRACTOR-ZIP              
CONTRACTOR-PHONE            
SQUARE-FOOTAGE              
STRUCTURE-UNITS             
STRUCTURE-FLOORS            
PERMIT-CATEGORIES PIC
LAST-INSPECTION-DATE        
LAST-APPROVED-INSP-DATE     
CO-CC-DATE                  
PERMIT-TOTAL-FEE

**Comment by ErnieAtLYD** [comment]
https://opendata.miamidade.gov/dataset/PermitDataSet/kw55-e2dj?

**NOTE:** Data does not show if you are not logged into socrata. Do not know if this is on purpose.

**EDITED:**  As of Monday 8/24 data set DOES work now. Removing blocked label.
