### ISSUE TITLE
Stand up textizen  (Due 5/29)

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#7]

**Comment by mathias-gibson** [comment]
ready and waiting for Nicole

**Comment by mathias-gibson** [comment]
“How would you rate your experience at the Miami-Dade County Permit Inspection Center?  Text a letter grade from A-F.”
“How many days, on average, does it take for you to get a permit approved?
“How could the County improve the process of getting a building permit?”
“Which of the following most accurately defines your primary role in your projects permitted at the County?”
A. tradesman/contractor
B. architect/designer
C. permit consultant/expediter
D. developer
E. homeowner
F. small business owner
“Can we contact you for more feedback about this issue? If yes, please reply with your email address or phone number.”
