### ISSUE TITLE
Get Plans Tracking Data

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#70]
Right now the dashboard makes references to Plans Status. How do we bring live data into this? What's the current situation? Can there be a stop-gap solution that can temporarily implemented so a flood of new things don't hit me at once?

Note that right now, the only data I'm aware of is the e-mail that Nancy Perez sends on a daily basis. I can parse the daily "FW: Status of Plans / MMNFP" e-mails. It's a brute force solution, so any information you can send me to parse the information, the better.

**Comment by mathias-gibson** [comment]
So right now the mainframe dataset on the open data portal just has an open
date, but I'm looking to add a closed date along with other status dates

Plans tracking, that populates that email from Nancy, is in a different
database, and I'm not sure about our access there quite yet.

**Comment by mathias-gibson** [comment]
sending message off to Donna, not sure if CIAO has this yet...

**Comment by ErnieAtLYD** [comment]
Still nothing, right? May need to remind Sarasti that this would prevent several pieces of functionality from happening if we don't get this.

**Comment by mathias-gibson** [comment]
nothing yet, havent heard from him this week

**Comment by sarasti** [comment]
Guys - we're having a major issue with Socrata so all hands are on deck for that. Your base permitting data set is dependent on this environment working. As soon as we can get this cleanly uploaded, I'll have Yanelis target plans tracking.

**Comment by ErnieAtLYD** [comment]
From Sarasti today: "Hey guys - working on Plans Tracking today... they've supposedly given us access but we're still having connection issues. YAnelis has reached out to Syed (who's out for the week, but replying to email) for some advice."
