### ISSUE TITLE
What do we think about changing the opinion scale from 1-5 to 1-7?

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#78]
@daguar mentioned he uses a 1-7 scale, and Shelly wrote the following: "I use scale of 1-7, because  scale of 1-10 makes people think in terms of letter grades, and so they'll rarely say anything below a 6 or 7. Scale of 1-5 doesn't give people enough options."

Worth implementing?

**Comment by mathias-gibson** [comment]
Yeah, I just used 1-5 as a default, happy incorporate other people's wisdom, I'll change them all to 1-7

**Comment by daguar** [comment]
:+1:
