### ISSUE TITLE
Stand up Cityvoice (Due 5/29)

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#8]

**Comment by daguar** [comment]
Oh hai cc @jmadans

**Comment by mathias-gibson** [comment]
attempted to stand up city voice, after recording last audio clip i got an internal server error, so we’ll have to wait for them to fix it before deploying

**Comment by daguar** [comment]
Did this happen today or was this before?

**Comment by jmadans** [comment]
This was today.
![internal_error](https://cloud.githubusercontent.com/assets/1261618/7779569/7a7e1670-008a-11e5-8ead-75188c2cf93b.png)

**Comment by mathias-gibson** [comment]
this was today, happened in the builder, Internal Server Eror

**Comment by jmadans** [comment]
@daguar Feel no need to troubleshoot. I will try with @migurski first next week!

**Comment by daguar** [comment]
Something's up with Redis — the errors are all `TypeError - no implicit conversion of nil into String` where the builder is trying to `JSON.parse` JSON from Redis.

The Redis expiration is currently 30 minutes, but that's an open issue specified here: https://github.com/codeforamerica/cityvoice-survey-builder/issues/8

**Comment by daguar** [comment]
Did we figure out what the bug was here?
