### ISSUE TITLE
Do we care if admins can rearrange and choose widgets?

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#87]
- Should admins be able to choose the order of dashboard widgets?
- Should admins be able to add or remove dashboard widgets on demand?

If the above two answers are "yes", I'm assuming should anyone with the proper permissions should be able to set a view that anyone going to the dashboard can see. 

Also, if this is the case, this probably means a lot more control will be moved from the python side to the javascript side. There may need to be a giant javascript object, and then in JS each of those widgets may have to be dynamically created for the dashboard to display. Not 100% sure yet of the implementation however.

**Comment by phiden** [comment]
That's pretty much what I was thinking -- that they'd have control. We have options, though. We can move that to v2 and out of our MVP, for one. For two, we can move it to JS -- I'm happy to take over at least the move-ability of that.

**Comment by ErnieAtLYD** [comment]
Now that #111 is spun off I'm closing this.
